databases:
  - name: PostgreSQL
    ipAllowList: []
    databaseName: video_gallery
    user: my_app_render

services:
  - type: web
    name: my_app_render
    env: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: PostgreSQL
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false